version: 2
updates:
  - package-ecosystem: pip
    directory: /
    target-branch: integration/nightly
    schedule:
      interval: weekly
      day: monday
      time: "03:00"
      timezone: Europe/Moscow
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - python

  - package-ecosystem: github-actions
    directory: /
    target-branch: integration/nightly
    schedule:
      interval: weekly
      day: monday
      time: "03:30"
      timezone: Europe/Moscow
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
